root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './tsconfig.json'
    - './tsconfig.jest.json'

plugins:
  - '@typescript-eslint'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'

ignorePatterns:
  - 'dist'
  - 'node_modules'

rules:
  quotes: [error, single]
