root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './tsconfig.json'
    - './tsconfig.jest.json'

plugins:
  - '@typescript-eslint'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'

ignorePatterns:
  - 'lib'
  - 'examples'
  - 'node_modules'

rules:
  quotes: [ error, single ]
  quote-props: [ error, as-needed ]

overrides:
  - files:
      - '*.test.ts'
    rules:
      '@typescript-eslint/no-unsafe-assignment': off
      '@typescript-eslint/unbound-method': off
